### ISSUE TITLE
Title and Heading Levels

### ISSUE THREAD

**Issue by ERyan71258** [SMPTE/html-pub#122]
In the sample document HTML code, the document title has an "&lt;h1&gt;" tag. What is Heading 1 is now "&lt;h2&gt;", Heading 2 is "&lt;h3&gt;", and so on. Is there a structural reason for doing this instead of using a different tag for the title, e.g., "&lt;smptedoctitle&gt;", and maintaining the correspondence between the heading number and its HTML tag? I know that the "&lt;title&gt;" tag is used as the metadata tag for the name of the document, so it would require the creation a new tag, but I don't see that as a difficulty.

I would think that maintaining the correspondence between the heading tag number, e.g., "&lt;h3&gt;", with its Word heading number, "Heading 3", would make sense, especially when updating existing documents (especially with multiple outline levels), and even when creating new ones. We are all accustomed to main clauses formatted as Heading 1, which would be "&lt;h1&gt;" in the HTML version.

From the logical standpoint of editing the document, "&lt;h1&gt;" would have one number (e.g. "3"), "&lt;h2&gt;" would have two numbers (e.g., "3.2"), and "&lt;h3&gt;" would have three numbers (e.g., "3.5.12"), etc.

**Comment by palemieux** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements#avoid_using_multiple_h1_elements_on_one_page
