### ISSUE TITLE
Add math element and formula numbering

### ISSUE THREAD

**Issue by ERyan71258** [SMPTE/html-pub#145]
Add instructions as to how to add a math element and formula numbering.

**Comment by palemieux** [comment]
See https://doc.smpte-doc.org/html-pub/main/#sec-formulae

**Comment by ERyan71258** [comment]
I created a Math section in a copy of mail.html, and pasted the code from the above link.
The italic does not display, nor does the superscript.
Also, there should be a space to the left and right of each operator.
![image](https://github.com/SMPTE/html-pub/assets/118845840/7f585790-e2cb-4ef7-a6a8-7534f965a6cc)

The italic and superscript do display in an external browser:
![image](https://github.com/SMPTE/html-pub/assets/118845840/914eada2-aff5-46f2-8c8a-cb72dd289f27)

For ease of editing, the italic, superscript, and any other such styles should display in the internal browser.

**Comment by palemieux** [comment]
@ERyan71258 Does the example at https://doc.smpte-doc.org/html-pub/main/#sec-formulae show up correctly in your browser?

**Comment by ERyan71258** [comment]
Yes, the link that you provided displays fine in Edge, Chrome and Mozilla on my laptop, and in Safari and Chrome on my iPhone.

When I copied the code into VSC, it did not display correctly in Preview, but displayed fine in Edge, Chrome and Mozilla. The issue appears to be confined only to the VSC Preview.

**Comment by palemieux** [comment]
> The issue appears to be confined only to the VSC Preview.

Oh. That is unfortunate.  I personally use an external browser window: `Ctrl + Shift P -> Live preview: preview in external browser`

**Comment by ERyan71258** [comment]
Then users should be advised to check math displays in an external browser. In the end, it is a good idea to check the display of a document in external browsers.

Nice formula auto-numbering!
