### ISSUE TITLE
Code snippets question

### ISSUE THREAD

**Issue by ERyan71258** [SMPTE/html-pub#146]
If adding a code snippet via an external file, does it become an additional element and must it be listed as such in an Additional Elements annex?

**Comment by palemieux** [comment]
Snippets are edited as separate documents (on the file system) but inserted in the main prose element at rendering time, i.e. they are not published as separate documents. Snippets are just editorial sugar, and therefore not additional elements.

**Comment by ERyan71258** [comment]
Thanks. Then editors will not get wrapped around whether or not to list
them.

"Editorial sugar" - that is a new one. I will have to remember it.

**Comment by palemieux** [comment]
@ERyan71258 Can you review the proposed clarification at https://github.com/SMPTE/html-pub/pull/147 ? Thanks!

**Comment by ERyan71258** [comment]
Will changes be tracked in code snippets in a similar manner as changes tracked in the main text?

**Comment by palemieux** [comment]
> Will changes be tracked in code snippets in a similar manner as changes tracked in the main text?

Yes. The snippet get merged into the text by the tooling.

**Comment by ERyan71258** [comment]
Thanks.
