### ISSUE TITLE
Make the state and stage of the document more obvious

### ISSUE THREAD

**Issue by palemieux** [SMPTE/html-pub#158]
The stage (WD, CD, FCD...) and the status (approved, draft) should be more obvious:

- the stage of the document should be larger and spelled out
- the "not-yet-published" box notice should be before the ToC
- draft documents should be labeled "not approved"

![image](https://github.com/SMPTE/html-pub/assets/4871350/f20b21b7-f303-4228-8242-3d3401a5b456)

![image](https://github.com/SMPTE/html-pub/assets/4871350/e5be578a-8b2d-46ff-ab10-5d353b0b9569)

**Comment by SteveLLamb** [comment]
We also need the following:
- `pubStage` value of `PCD`
- For `PCD`
 - prior to the ToC with the warning box, the `CONTRIBUTING.md`, `LICENSE.md`, and `PATENTS.md` rendered into the doc
 - watermark enabled - the `draft` one we use on `draft` `pubState` should suffice

**Comment by palemieux** [comment]
"PCD" is not a formal document stage in the process. A "PCD" is in fact a Committee Draft (CD). What is the rationale for informing the reader that SMPTE has an internal procedure called "PCD"?

**Comment by palemieux** [comment]
`CONTRIBUTING.md` is only relevant for contributions to the repo, e.g. when filing an issue. It is not relevant to to document itself.

**Comment by palemieux** [comment]
`PATENTS.md` is intended to be included in the repo. It is redundant within the document, which already contains the following notice:

>At the time of publication no notice had been received by SMPTE claiming patent rights essential to the implementation of this Engineering Document. However, attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. SMPTE shall not be held responsible for identifying any or all such patent rights.

**Comment by palemieux** [comment]
> LICENSE.md

`LICENSE.md` is intended to be included in the repo. It is redundant within the document, which already contains the following copyright notice:

> Copyright © 2023 SMPTE, 45 Hamilton Ave., White Plains NY 10601, (914) 761-1100.

**Comment by palemieux** [comment]
> watermark enabled - the draft one we use on draft pubState should suffice

The watermark makes it very difficult to read.

What about adding the document stage to the page header?
