### ISSUE TITLE
Improve reporting of empty anchors

### ISSUE THREAD

**Issue by thomasheritage** [SMPTE/html-pub#171]
The HTML:
```
<a></a>
```
currently results in:
```
Unresolved link (link)
```
being reported in the floating red rectangle.

Should this instead be reported as an "empty anchor"? It looks like [the code](https://github.com/SMPTE/html-pub/blob/42ad94f33eb07309f2d70999b422d2f6bb765716/smpte.js#L1163C29-L1163C29) has an "empty anchor" case, but that outcome is not reached for the provided HTML.

**Comment by palemieux** [comment]
Couple of improvements:

* in the case of `<a>xxx</a>` where `xxx` is not a defined term, the error should be "A definition for xxx does not exist."
* in the case of `<a></a>`, the error should be "An anchor must either reference a definition (non-empty contents) or link to a resource (non-empty href attribute."
