### ISSUE TITLE
Use "AG-xx" or "AG xx"?

### ISSUE THREAD

**Issue by thomasheritage** [SMPTE/html-pub#172]
The standard number is rendered in the top-right of the document e.g. "SMPTE AG 18".

However, it is often common practice to use the form "AG-18" for AGs i.e. with a hyphen.

The definition in [AG 02](https://doc.smpte-doc.org/ag-02/4628671d8020a800414a7f3e6d21f042e4e9fc00/) gives the un-hyphenated form.

However, the hyphenated form is used on https://www.smpte.org/2020-standard-policies-and-governance (which links to all the rendered AGs).

And AG 02 itself refers to "AG-03" and "AG-04"...

Should the un-hyphenated form be used throughout?

**Comment by palemieux** [comment]
> Should the un-hyphenated form be used throughout?

Yes in my opinion, just like ST 2001 is not written ST-2001.
