### ISSUE TITLE
Issues specific to the PDF

### ISSUE THREAD

**Issue by ERyan71258** [SMPTE/html-pub#196]
The following issues apply to the PDF version of this document:
General:
- TOC should have dotted line leaders to the page numbers for those who print.
- Page numbering is all odd, as opposed to odd/even. The first page numbering is also not different. Is this intentional?
- Header is missing the year.
- Should be able to either insert a page break (not my favorite solution) or add a Keep with Next to paragraphs and table rows to keep them together when generating to PDF. Headings should also automatically be tagged as Keep with Next, as in the PDF, they separate from following subheadings and text.
- When tables split, the heading row is not repeated at the top of the following page, and the table dimensions change on the following page.

Title Page:
- I am not sure if this was an error that was already fixed or not, as it does appear in the web version, but the document number at the top right is missing the date:
![image](https://github.com/SMPTE/st429-4/assets/118845840/ad27fef7-9e04-4073-8b01-ebe7691a1ba1)
- First page is missing the SMPTE contact information, i.e., the address and phone number. We should also include the website.

7.5.2 Table 4:
I am not sure if this had been changed in the web version after the PDF was created, because the web version looks fine:
![image](https://github.com/SMPTE/st429-4/assets/118845840/05b2b150-da8c-4cdd-ab4d-8df2c00f90eb)
The PDF, however, appears to be missing information in the second-to-last row, Columns 1 and 2:
![image](https://github.com/SMPTE/st429-4/assets/118845840/6ff11a75-737f-44ce-8f54-6c916190b7e3)

**Comment by SteveLLamb** [comment]
This looks duplicated to https://github.com/SMPTE/html-pub/issues/199, and many other issues have been already been broken out and/or resolved. Can we can confirm and move as needed?

**Comment by SteveLLamb** [comment]
Closing as duplicate, and remaining Issues broken out as:
- TOC formatting https://github.com/SMPTE/html-pub/issues/196
- Odd page numbers https://github.com/SMPTE/html-pub/issues/226
- Header year info resolved in past tooling updates
- Page breaks and KWN: https://github.com/SMPTE/html-pub/issues/234 https://github.com/SMPTE/html-pub/issues/253 https://github.com/SMPTE/html-pub/issues/107
- Repeating table headers https://github.com/SMPTE/html-pub/issues/260
- Year info resolved in past tooling updates
- Contact info: https://github.com/SMPTE/html-pub/issues/254
