### ISSUE TITLE
Issues specific to the ST429-6 PDF

### ISSUE THREAD

**Issue by ERyan71258** [SMPTE/html-pub#199]
The following issues apply to the PDF version of this document:
General:
- TOC should have dotted line leaders to the page numbers for those who print.
- Page numbering is all odd, as opposed to odd/even. The first page numbering is also not different. Is this intentional?
- Header is missing the year.
- Should be able to either insert a page break (not my favorite solution) or add a Keep with Next to paragraphs and table rows to keep them together when generating to PDF. Headings should also automatically be tagged as Keep with Next, as in the PDF, they separate from following subheadings and text.
- When tables split, the heading row is not repeated at the top of the following page, and the table dimensions change on the following page.
- Many of the graphics are not of good quality in the web version, but they look even worse in the PDF, especially where kerning is concerned. The characters are also stair-stepped, with no antialiasing.

Title Page:
- I am not sure if this was an error that was already fixed or not, as it does appear in the web version, but the document number at the top right is missing the date:
![image](https://github.com/SMPTE/st429-6/assets/118845840/184a90c5-0ed3-4d7e-845c-34341cb9dd40)
- First page is missing the SMPTE contact information, i.e., the address and phone number. We should also include the website.

**Comment by palemieux** [comment]
![image](https://github.com/SMPTE/html-pub/assets/4871350/ae6a332d-09f8-47c4-bccd-f54540245d0d)

**Comment by SteveLLamb** [comment]
This looks duplicated to https://github.com/SMPTE/html-pub/issues/196, and many other issues have been already been broken out and/or resolved. Can we can confirm and move as needed?

**Comment by ERyan71258** [comment]
Yes, can move ahead.

**Comment by SteveLLamb** [comment]
Thanks, closing as duplicate.
