### ISSUE TITLE
Conversion of Word to HTML Lacks Section Elements

### ISSUE THREAD

**Issue by bgschunck** [SMPTE/html-pub#2]
Used simple pandoc command to convert Word document to HTML. The output did not include the <section> elements that are required for ReSpec to create the table of contents. If the section element is missing, then the corresponding section heading will not appear in the table of contents.

The pandoc tool converts headings to &lt;h2 id='section-name'&gt; while ReSpec needs &lt;section id='section-name'&gt;&lt;h2&gt;

The Word and HTML documents are checked into SG Software on Workspace under the names SMPTE Software Best Practices.

**Comment by SteveLLamb** [comment]
Close, will not fix. Using different HTML methods.
