### ISSUE TITLE
Title Area - HTML - Missing Date in Document Number

### ISSUE THREAD

**Issue by ERyan71258** [SMPTE/html-pub#207]
The date is missing from the document number. Not all HTML documents display this error, but many do.
![image](https://github.com/SMPTE/html-pub/assets/118845840/06734d90-687d-42cd-8202-3812e786a4b9)

**Comment by SteveLLamb** [comment]
I cannot locate this in any current version that has a pub package. This will only appear without a date in the case where `pubStage` is not equal to `PUB` or `pubState` is `draft`. @palemieux please confirm this, and we can close this.

**Comment by palemieux** [comment]
Closed by f9c39f5528b91788056498ac10a1e8da18cd7b2c
