### ISSUE TITLE
HTML heading levels do not match TOC level

### ISSUE THREAD

**Issue by dcbullock** [SMPTE/html-pub#23]
Unless I am mistaken, the "h" tags in the HTML source do not match the TOC level.

H2 for example is used for a top-level, single digit TOC entry.  H3 for double-digit (1.2).  Etc...

Is there a reason we started with H2 instead of H1?

It causes a bit friction when tracking down open and close sections that are messed up.  We should consider matching "h" levels with TOC levels before we get too far along the HTML path.  This will come up in ST at some point.

**Comment by palemieux** [comment]
`h1` corresponds to the title of the document.

**Comment by dcbullock** [comment]
I see that now in the front-matter.  Thank you.  H1 would be way to big for level-one entries in any case.  I think this can be closed as don't fix unless others think it is worth getting clever with the CSS to define a custom entry for the title in the front-matter and resize the H1-H5 tags.

Now that I have had this discussion, I will likely never get tripped up again...
