### ISSUE TITLE
referencing Annex B.6 says "Clause B.6" instead of "B.6"

### ISSUE THREAD

**Issue by michaeldsmith** [SMPTE/html-pub#298]
I'm working on porting 2067-21:2023 to HTML workflow

This line of code https://github.com/SMPTE/st2067-21-private/blob/052d0ff4243bd29a677174ebc3f3284488f21ea2/doc/main.html#L786

`<p>Note 1: <a href="#sec-mastering-display-color-volume-metadata-mastering-display-examples"></a> contains selected examples values for Mastering Display Color Volume Metadata. Other values, not specified in these examples, are also permitted.</p>`

renders to HTML like this:

![image](https://github.com/user-attachments/assets/1c739528-a015-4748-b2e2-863c5040c6c5)

In PDF from 2023 it looks like this:
![image](https://github.com/user-attachments/assets/e0becdfe-741d-46b1-9f80-7b7e48eba3b8)

@palemieux says it should just say "B.6"

**Comment by palemieux** [comment]
Turns out that the ISO guidelines (under "Annex -> Specific principles and rules") says that "Clause B.6" is the right notation.
