### ISSUE TITLE
Determine required sections for AG docs

### ISSUE THREAD

**Issue by SteveLLamb** [SMPTE/html-pub#30]
Agree on and update index template for AG sections.

**Comment by SteveLLamb** [comment]
Current rendered, recommendations in (), and order from template and based on current docs:

- Forward (required)
- Introduction (optional? Only one document has this currently)
- TOC (required)
- Scope (required, labeled Purpose on some docs, should be updated to Scope)
- Conformance (required, auto removes section about Engineering Docs in "AG" doc type) 
- Normative References (optional)
- Terms and Definitions (optional)
- Abbreviated Terms (one doc has this, should it be rolled into Term and Definitions?)

Then main body sections and annexes as required.

**Comment by dcbullock** [comment]
> Current rendered, recommendations in (), and order from template and based on current docs:
> 
>     * Forward (unnumbered, required)
Concur.

> 
>     * Introduction (unnumbered, optional? Only one document has this currently)
The AG-18 Introduction can be rolled into its Scope section.  I think we should drop introduction.

>     * TOC (unnumbered, required)
Concur.

> 
>     * Scope (required, labeled Purpose on some docs, should be updated to Scope)
Concur.

> 
>     * Conformance (required, auto removes section about Engineering Docs in "AG" doc type)
Concur.

> 
>     * Normative References (optional)
I think we should leave this section in with a place holder when it is empty.  Having all of the AGs start with the same set of sections makes it that much easier for future editors to understand how to start an AG.

> 
>     * Terms and Definitions (optional)
Same as Normative Refs.

> 
>     * Abbreviated Terms (one doc has this, should it be rolled into Term and Definitions?)
Abbreviations for terms should be done as a part of the Terms and Defs section.  We can build on the tooling to make this more useful in terms of anchors and links.  No need for a another section with abbreviations.

> 
> 
> Then main body sections and annexes as required.

For the same reasoning as including an empty normative references, I think we should include a biblio section with a placeholder for AGs that don't have any bibliographic entries.

**Comment by SteveLLamb** [comment]
> I also like the to see the same pattern repeated in different documents. There is a piece of my brain that gets uncomfortable when I am reading an ST or AG and I can't find a common section like normative references. Did they forget it? Who authored this? Etc...

Agreed. I think there is some text is the ISO guidelines such as "there are none... blah blah". I'll look this up tomorrow or Friday and respond with verbiage in the thread.

**Comment by dcbullock** [comment]
The ISO .doc example document includes the following for empty sections.


# normative references
There are no normative references in this document.

# terms and definitions
No terms and definitions are listed in this document.

# bibliographic
The ISO example does not include this section, I recommend similar wording as the normative references.
_There are no bibliographic references in this document._

**Comment by SteveLLamb** [comment]
Unless any objections by Monday 9/26, I will incorporate this into the html-pub and html-pub-template repos.

**Comment by billredmann** [comment]
Is the TOC as item 3 in the list something from ISO to which we're swearing fealty?  In looking at old and recent SMPTE AGs & engineering docs (including the 2020 AG-04 templates), TOC is the first item.  The Foreword section is singularly uninteresting, making for a dull first page.  Common use case - looking for a <thing>, opening a doc and clicking <thing> in the TOC.

**Comment by billredmann** [comment]
Were these changes to section titles something from ISO?
  Normative References -> Normative references
  Conformance Notation -> Conformance
  Bibliography (informative) -> Bibliography

**Comment by SteveLLamb** [comment]
> 

Yes, the capitalization style is directly from the ISO Directives part 2.

**Comment by SteveLLamb** [comment]
> Is the TOC as item 3 in the list something from ISO to which we're swearing fealty? In looking at old and recent SMPTE AGs & engineering docs (including the 2020 AG-04 templates), TOC is the first item. The Foreword section is singularly uninteresting, making for a dull first page. Common use case - looking for a [thing], opening a doc and clicking [thing] in the TOC.

Yes, looking at the ISO Directive again, TOC should probably be first. I'll re-list everything for a good summary, to discuss tomorrow's ST call.

**Comment by SteveLLamb** [comment]
Full list or sections, all sections mandatory and present. 

- _Table of contents_ 
-- (unnumbered, no header)
- _Forward_ 
-- (unnumbered)
- _Scope_
- _Conformance_
- _Normative references_
-- If no references exist, include the following phrase below the clause title: "There are no normative references in this document."
- _Terms and definitions_ 
-- (abbreviated terms included)
-- if there are no terms and definitions provided, use the following introductory text: "No terms and definitions are listed in this document."
- _1-XX Section name_ 
-- Main Numbered Sections
- _Annex A-Z_
-- (optional)
- Bibliography
-- If no bibliographic references exist, include the following phrase below the clause title: "There are no bibliographic references in this document."

**Comment by SteveLLamb** [comment]
Updated commit in #27 as noted above.
