### ISSUE TITLE
Add missing doc metadata to header

### ISSUE THREAD

**Issue by SteveLLamb** [SMPTE/html-pub#60]
```
<meta itemprop="pubPart" content="XX" />
<meta itemprop="pubElement" content="XX" />
```

**Comment by palemieux** [comment]
In what circumstance would `pubElement` be used?

**Comment by palemieux** [comment]
I do not think supporting old engineering documents is within the scope of this tooling.

**Comment by SteveLLamb** [comment]
`pubPart` included in https://github.com/SMPTE/html-pub/pull/89
